#!/bin/sh
# device-unifier.sh — Canonical Device Identity & MAC Rotation Correlator
#
# Tracks real physical devices across MAC address rotations (Private Wi-Fi).
# Maps multiple historical/rotating MACs to one Canonical Device and merges usage.

set -u

IDENTITIES_TSV="${IDENTITIES_TSV:-/etc/usage-log/device-identities.tsv}"
mkdir -p "$(dirname "$IDENTITIES_TSV")" 2>/dev/null || true

# Sync /etc/ethers so LuCI hostHints and system ARP recognize all aliases
unifier_sync_ethers() {
    [ ! -f "$IDENTITIES_TSV" ] && return 0
    [ ! -d "/etc" ] && return 0
    local tmp_ethers="/tmp/ethers.$$"
    echo "# Generated by device-unifier.sh" > "$tmp_ethers" 2>/dev/null || return 0
    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        old_ifs="$IFS"
        IFS=','
        for m in $macs; do
            [ -n "$m" ] && echo "$m	$name" >> "$tmp_ethers"
        done
        IFS="$old_ifs"
    done < "$IDENTITIES_TSV"
    mv -f "$tmp_ethers" /etc/ethers 2>/dev/null || rm -f "$tmp_ethers"
}

# Seed default household devices if inventory does not exist
unifier_init_defaults() {
    if [ -s "$IDENTITIES_TSV" ]; then
        unifier_sync_ethers
        return 0
    fi
    mkdir -p "$(dirname "$IDENTITIES_TSV")" 2>/dev/null || true
    cat << 'EOF' > "$IDENTITIES_TSV" 2>/dev/null || return 0
dev-lenovo	Lenovo-Legion	parsa	Laptop	a8:2b:dd:8c:cf:fc
dev-nothing	Nothing-Phone-2	parsa	Phone	22:7d:f2:30:d3:3b,42:08:7c:71:a1:b4
dev-iphone	parsavisions-wifi	parsa	Phone	f4:28:9d:60:61:cb,da:13:07:c4:1a:22,4a:e1:8c:80:1a:7e
dev-redmi	Redmi-Note-9S	parsa	Phone	16:f7:3c:47:fd:30,7a:31:39:d7:2c:42
dev-samsung	Samsung-TV	family	TV	c8:12:0b:32:7c:f2
dev-androidbox	Android-Box	family	TVBox	c4:46:19:7e:c5:44
dev-pc	WIN10-PC	baba	PC	10:02:b5:ac:c1:e1,5c:a6:e6:df:91:d1
EOF
    unifier_sync_ethers
}

# Normalize MAC
norm_mac() {
    printf '%s' "$1" | tr 'A-F' 'a-f'
}

# Find canonical name for a given MAC
unifier_get_canonical() {
    local target_mac
    target_mac=$(norm_mac "$1")
    [ -z "$target_mac" ] && return 1
    unifier_init_defaults

    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        case ",$macs," in
            *,"$target_mac",*)
                echo "$name"
                return 0
                ;;
        esac
    done < "$IDENTITIES_TSV"
    return 1
}

# Find canonical device ID for a given MAC
unifier_get_id() {
    local target_mac
    target_mac=$(norm_mac "$1")
    [ -z "$target_mac" ] && return 1
    unifier_init_defaults

    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        case ",$macs," in
            *,"$target_mac",*)
                echo "$dev_id"
                return 0
                ;;
        esac
    done < "$IDENTITIES_TSV"
    return 1
}

# Link a MAC address to a target device (by ID or Display Name)
unifier_link_mac() {
    local target_mac target_dev
    target_mac=$(norm_mac "$1")
    target_dev="$2"
    [ -z "$target_mac" ] || [ -z "$target_dev" ] && return 1
    unifier_init_defaults

    local found=0
    local tmp_file="$IDENTITIES_TSV.tmp"
    rm -f "$tmp_file"

    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        if [ "$dev_id" = "$target_dev" ] || [ "$name" = "$target_dev" ]; then
            found=1
            # Add MAC if not already present
            case ",$macs," in
                *,"$target_mac",*)
                    echo "$dev_id	$name	$owner	$dtype	$macs" >> "$tmp_file"
                    ;;
                *)
                    echo "$dev_id	$name	$owner	$dtype	$macs,$target_mac" >> "$tmp_file"
                    ;;
            esac
        else
            # Remove target_mac from any other device to prevent duplicates
            local clean_macs
            clean_macs=$(echo ",$macs," | sed "s/,$target_mac,/,/g" | sed 's/^,//;s/,$//')
            echo "$dev_id	$name	$owner	$dtype	$clean_macs" >> "$tmp_file"
        fi
    done < "$IDENTITIES_TSV"

    if [ "$found" -eq 1 ]; then
        mv -f "$tmp_file" "$IDENTITIES_TSV"
        unifier_sync_ethers
        echo "OK: Linked $target_mac -> $target_dev"
        return 0
    else
        rm -f "$tmp_file"
        echo "ERR: Device $target_dev not found" >&2
        return 1
    fi
}

# Unlink a MAC from any device
unifier_unlink_mac() {
    local target_mac
    target_mac=$(norm_mac "$1")
    [ -z "$target_mac" ] && return 1
    unifier_init_defaults

    local tmp_file="$IDENTITIES_TSV.tmp"
    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        local clean_macs
        clean_macs=$(echo ",$macs," | sed "s/,$target_mac,/,/g" | sed 's/^,//;s/,$//')
        echo "$dev_id	$name	$owner	$dtype	$clean_macs" >> "$tmp_file"
    done < "$IDENTITIES_TSV"
    mv -f "$tmp_file" "$IDENTITIES_TSV"
    unifier_sync_ethers
    echo "OK: Unlinked $target_mac"
}

# Auto-link on DHCP lease: correlates new rotating MAC via Hostname / PRL
unifier_auto_link() {
    local mac host prl vci
    mac=$(norm_mac "$1")
    host="${2:-}"
    prl="${3:-}"
    vci="${4:-}"
    [ -z "$mac" ] && return 0
    unifier_init_defaults

    # 1. If already linked, nothing to do
    if unifier_get_canonical "$mac" >/dev/null 2>&1; then
        return 0
    fi

    local matched_target=""

    # 2. Correlate by hostname
    case "$host" in
        *Nothing*|*nothing*)
            matched_target="Nothing-Phone-2" ;;
        *parsavisions*|*iPhone*|*iphone*)
            matched_target="parsavisions-wifi" ;;
        *Redmi*|*redmi*|*Xiaomi*|*xiaomi*)
            matched_target="Redmi-Note-9S" ;;
        *WIN*|*DESKTOP-*)
            matched_target="WIN10-PC" ;;
        *Samsung*|*[TV]*)
            matched_target="Samsung-TV" ;;
        *Lenovo*|*Legion*|*ThinkPad*)
            matched_target="Lenovo-Legion" ;;
    esac

    # 3. Apply link if match found
    if [ -n "$matched_target" ]; then
        unifier_link_mac "$mac" "$matched_target" >/dev/null 2>&1
        echo "AUTO-LINK: Associated rotating MAC $mac -> $matched_target (via host: $host)"
        return 0
    fi
}

# Display current canonical devices and their linked MACs
unifier_list() {
    unifier_init_defaults
    printf '%-18s %-20s %-8s %-8s %s\n' "ID" "NAME" "OWNER" "TYPE" "LINKED MACS"
    printf '%-18s %-20s %-8s %-8s %s\n' "------------------" "--------------------" "--------" "--------" "----------------------------------------"
    while IFS="$(printf '\t')" read -r dev_id name owner dtype macs; do
        printf '%-18s %-20s %-8s %-8s %s\n' "$dev_id" "$name" "$owner" "$dtype" "$macs"
    done < "$IDENTITIES_TSV"
}

case "${1:-list}" in
    get)
        shift
        unifier_get_canonical "$1"
        ;;
    get-id)
        shift
        unifier_get_id "$1"
        ;;
    link)
        shift
        unifier_link_mac "$1" "$2"
        ;;
    unlink)
        shift
        unifier_unlink_mac "$1"
        ;;
    auto-link)
        shift
        unifier_auto_link "$@"
        ;;
    list)
        unifier_list
        ;;
    init)
        unifier_init_defaults
        ;;
    *)
        echo "usage: $0 {get <mac>|link <mac> <dev>|unlink <mac>|auto-link <mac> [host] [prl] [vci]|list|init}"
        exit 1
        ;;
esac
