#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/local/bin/dnstt-client

start_service() {
    config_load 'dnstt'
    local enabled domain pubkey_file resolver listen_addr

    config_get_bool enabled main enabled 1
    [ "$enabled" -eq 1 ] || return 0

    config_get domain main domain 't.dmbz.ir'
    config_get pubkey_file main pubkey_file '/etc/dnstt/server.pub'
    config_get resolver main resolver '1.1.1.1:53'
    config_get listen_addr main listen_addr '127.0.0.1:5300'

    [ -f "$PROG" ] || return 1
    [ -f "$pubkey_file" ] || return 1

    procd_open_instance
    procd_set_param command "$PROG" -udp "$resolver" -pubkey-file "$pubkey_file" "$domain" "$listen_addr"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
