#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /data/proxy/v2raya
    procd_append_param command --config /etc/v2raya
    procd_append_param command --v2ray-bin /data/proxy/xray
    procd_append_param command --core-type xray
    procd_append_param command --v2ray-assetsdir /data/proxy
    procd_append_param command --log-file /tmp/v2raya.log
    procd_append_param command --log-level info
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
