#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=12

start_service() {
    procd_open_instance
    procd_set_param command /data/proxy/xray
    procd_append_param command run
    procd_append_param command -config /data/proxy/sing-box/xray-split.json
    procd_set_param env XRAY_LOCATION_ASSET=/data/proxy
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
